theme: jekyll-theme-slate
title: Power System Blocks
show_downloads: false

github:
  repository_name: Powsybl website
  repository_url: https://github.com/powsybl
  owner_name: RTE France
  owner_url: https://www.rte-france.com
